### PR TITLE
fix: prevent ariadne from panicking on empty stdin/file

### LINKED ISSUE #78: Crash when passing empty string in stdin
Steps to reproduce:
```sh
echo "" | RUST_BACKTRACE=full statix check -s
```
Results in
```
[E00] Error: Syntax error
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /build/statix-0.5.6-vendor.tar.gz/ariadne/src/source.rs:109:25
stack backtrace:
   0:     0x55be76e9309c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2ea00d5f3b53d9f
   1:     0x55be76ec4c1e - core::fmt::write::ha076a7e65c6b1874
   2:     0x55be76ea51e1 - std::io::Write::write_fmt::h9630bb3b0fe886f5
   3:     0x55be76ead0b5 - std::panicking::default_hook::{{closure}}::h64163197f96398c1
   4:     0x55be76eacd12 - std::panicking::default_hook::h92625161492e6b48
   5:     0x55be76ead5d1 - std::panicking::rust_panic_with_hook::hfdd7d6bb6788c6c2
   6:     0x55be76e933d7 - std::panicking::begin_panic_handler::{{closure}}::he81a60a7ef84ad4a
   7:     0x55be76e931b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h62801bf9780239e6
   8:     0x55be76ead282 - rust_begin_unwind
   9:     0x55be76d07cc3 - core::panicking::panic_fmt::hfd221b9f37504b4a
  10:     0x55be76d07c02 - core::panicking::panic_bounds_check::hd62ce49e2c7e15d6
  11:     0x55be76d6ba3c - ariadne::source::Source::get_offset_line::hff6557d6c6989d76
  12:     0x55be76d0fa9d - ariadne::write::<impl ariadne::Report<S>>::write::h6d21c3b3fc711aae
  13:     0x55be76d1c0bd - statix::traits::write_stderr::hf326e6e9162805f2
  14:     0x55be76d366e0 - statix::lint::main::main::h02d93095411c466b
  15:     0x55be76d0b3b1 - statix::main::h75b6529e2c6a3a28
  16:     0x55be76d09243 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd0a11a681f67d665
  17:     0x55be76d09d29 - std::rt::lang_start::{{closure}}::h4151b7edf354832b
  18:     0x55be76e9e6b5 - std::rt::lang_start_internal::h09bcc9fffd987f14
  19:     0x55be76d0b5c2 - main
  20:     0x7f184c42924e - __libc_start_call_main
  21:     0x7f184c429309 - __libc_start_main_alias_1
  22:     0x55be76d07f05 - _start
  23:                0x0 - <unknown>
```
Expected result: 
Should return
```
[E00] Error: Syntax error
   ╭─[<stdin>:1:1]
   │
 1 │
   · │
   · ╰─ Unexpected end of file
───╯
```
as passing empty file would.

Additional context:
Providing empty empty file as input (not stdin) works, stdin with a single space character works as well. 

Output of `statix --version`:
```
statix 0.5.6
```

### PR DESCRIPTION
**Pull request by daschinmoy21**
Fixes https://github.com/oppiliappan/statix/issues/78

When statix receives an empty string via stdin, an empty Report is generated. Passing an empty string to ariadne's Source::from causes an index out of bounds panic. Supplying a string with a single space as a fallback prevents this panic while keeping the error location at byte offset 0.

Output after this fix-

 echo "" | nix run . -- check -s

[E00] Error: Syntax error
   ╭─[<stdin>:1:1]
   │
 1 │
   · │
   · ╰─ Unexpected end of file
───╯

### CODE REVIEW

**Comment by mightyiam** [comment]
How about a test for this?

**Comment by daschinmoy21** [comment]
Yea exactly i actually made a test last night. Will raise a pr in the evening after college ends

File: bin/src/traits.rs [hunk 1]
```diff
@@ -86,7 +86,10 @@ fn write_stderr<T: Write>(
                 },
             )
             .finish()
-            .write((src_id, Source::from(src)), &mut *writer)?;
+            .write(
+                (src_id, Source::from(if src.is_empty() { " " } else { src })),
```
Comment (mightyiam) [inline bin/src/traits.rs]: Why did you choose this workaround, please? Is there a more proper fix for this, please?

Comment (daschinmoy21) [reply bin/src/traits.rs]: The original issue mentioned the error occurred on no input "" but worked fine in stdin with a single space character. So i thought of replacing "" with " "

another way would be to return early
something like 
```if src.is_empty(){return Ok}``` but this results in no output at all in the cli when "" is passed.

Comment (mightyiam) [reply bin/src/traits.rs]: How is this handled in the file case?

Comment (daschinmoy21) [reply bin/src/traits.rs]: same behavior. No cli output on  a empty file. Returns error if the file has a space.

Comment (mightyiam) [reply bin/src/traits.rs]: Ahuh. Well, then I guess this should be ideally tested and fixed for both cases?

Comment (daschinmoy21) [reply bin/src/traits.rs]: Updated the code. Removed the empty-input mutation workaround and replaces it with a diagnostic fallback. the fix now preserves the original empty input and handles that case explicitly.
  
Works for stdin and files now.

also fixed the ci/cd error in the older commit.

File: bin/tests/_utils.rs
Comment (mightyiam) [inline bin/tests/_utils.rs]: Instead of a new test utility, can this be removed and handled more appropriately somehow?

Comment (daschinmoy21) [reply bin/tests/_utils.rs]: to reduce the duplication, ig a shared helper is the play, with a bool field for trailing newline.

File: bin/tests/_utils.rs [hunk 2]
```diff
@@ -1,11 +1,22 @@
...
+    expression: &str,
+    args: &[&str],
+    append_trailing_newline: bool,
+) -> anyhow::Result<String> {
     let mut fixture = NamedTempFile::with_suffix(".nix")?;
     fixture.write_all(expression.as_bytes())?;
-    fixture.write_all(b"\n")?; // otherwise diff says there's no newline at end of file
+    if append_trailing_newline {
+        fixture.write_all(b"\n")?; // otherwise diff says there's no newline at end of file
+    }
```
Comment (mightyiam) [inline bin/tests/_utils.rs]: Sorry, I suppose I wasn't clear enough. What I suggest we figure out is whether this appending of a line feed is necessary. I suspect there might be a better way.

Comment (daschinmoy21) [reply bin/tests/_utils.rs]: Dug around and the \n append is needed for fix --dry-run snapshot tests specifically. other tests are not affected.

maybe something like 
```rust
if args == ["fix", "--dry-run"] {
        fixture.write_all(b"\n")?;
    }
```

is a better choice in the helper?

If we want to remove the append entirely we have to update all affected fix --dry-run snapshots to include the no-trailing-newline diff 
so the snapshot would then look like this 
```
  -!(a == b)
  \ No newline at end of file
  +a != b
  \ No newline at end of file
```

Comment (mightyiam) [reply bin/tests/_utils.rs]: Or... perhaps test expressions can be modified to end with a line feed character and this workaround removed and the snapshots would end up with no change?

Comment (daschinmoy21) [reply bin/tests/_utils.rs]: It would generate new snapshots actually. snapshot name is based on a hash of the test expression token stream in ```macros/src/tests.rs```:
```rust
  let expression_hash = Sha256::digest(nix_expression.to_token_stream().to_string());
  let snap_name = format!("{kind_str}_{expression_hash}");
```
So changing test from  

``` !(a == b)```
  to:
  ```!(a == b)\n```
would create a new snapshot file entirely

Comment (mightyiam) [reply bin/tests/_utils.rs]: Theoretically, that would be okay. Practically, would git detect most of them as renames?

Comment (daschinmoy21) [reply bin/tests/_utils.rs]: tested in a separate worktree and yes git does detect it as a rename.

Comment (daschinmoy21) [reply bin/tests/_utils.rs]: but then removing the workaround and manually modifying the test expressions would also include checking the tests inside indoc! blocks as well in ```bin/tests/repeated_keys.rs```, maybe have to audit all the generated tests too.

Comment (mightyiam) [reply bin/tests/_utils.rs]: I think it's worth it. Doing the right thing usually is. But, perhaps we can see some partial progress on it and evaluate from there?

Comment (daschinmoy21) [reply bin/tests/_utils.rs]: alright will look more into this  but since it is a tests refactor at that point i think it makes more sense to
work on it as a separate PR.

Comment (mightyiam) [reply bin/tests/_utils.rs]: > separate PR

Good thinking

**Comment by mightyiam** [comment]
Some conflicts

**Comment by daschinmoy21** [comment]
On it

**Comment by daschinmoy21** [comment]
Should be good now. handles empty stdin and files now. Now it returns 
```
[E00] Error: Syntax error
   --> <stdin>:1:1
    |
    = Unexpected end of file
```

```
[E00] Error: Syntax error
   --> empty_nix_file.nix:1:1
    |
    = Unexpected end of file
```

File: bin/src/traits.rs [hunk 3]
```diff
@@ -49,8 +49,11 @@ fn write_stderr<T: Write>(
     let file_id = lint_result.file_id;
     let src = str::from_utf8(vfs.get(file_id)).unwrap();
     let path = vfs.file_path(file_id);
-    let range = |at: TextRange| at.start().into()..at.end().into();
     let src_id = path.to_str().unwrap_or("<unknown>");
+    if src.is_empty() {
+        return write_empty_stderr(writer, lint_result, src_id);
+    }
+    let range = |at: TextRange| at.start().into()..at.end().into();
```
Comment (mightyiam) [inline bin/src/traits.rs:52]: I'm picking up a certain smell here; isn't it strange that a `LintResult` exists for an empty source? I think an empty source should fail to parse. Does rnix successfully parse an empty string?

Comment (daschinmoy21) [reply bin/src/traits.rs:52]: Yes rnix  parses it. returns a ParseError::UnexpectedEOF

Comment (mightyiam) [reply bin/src/traits.rs:52]: So why are we getting this far in execution where a `LintResult` seems to exist?

Comment (daschinmoy21) [reply bin/src/traits.rs:52]: sorry,im confused, i dont understand what you mean? 
Empty input seems to follow the
same diagnostic path as other parse errors: rnix returns UnexpectedEOF, we convert that into a Report, and it ends up in LintResult. The empty-source branch in traits.rs is only there because ariadne panics on zero-length input, not because parsing succeeded

**Comment by daschinmoy21** [comment]
I checked the lock file and turns out ariadne crate quite outdated. statix is using v0.1.3. latest is 0.6.0 which also fixes the empty stdin panic we are trying to solve.  other additional change required would be in traits.rs,change
```
   CliReport::build(report_kind, src_id, offset)
```
to
```   
 CliReport::build(report_kind, (src_id, offset..offset))
```

Post update it now returns 
```
printf "" | cargo run -- check -s
    Finished [`dev` profile [unoptimized + debuginfo]](https://doc.rust-lang.org/cargo/reference/profiles.html#default-profiles) target(s) in 0.12s
     Running `target/debug/statix check -s`
[00] Error: Syntax error
   ╭─[ <stdin>:1:1 ]
   │
 1 │
   │ │
   │ ╰─ Unexpected end of file
```

File: bin/src/traits.rs [hunk 4]
```diff
@@ -67,7 +67,7 @@ fn write_stderr<T: Write>(
             .diagnostics
             .iter()
             .fold(
-                CliReport::build(report_kind, src_id, offset)
+                CliReport::build(report_kind, (src_id, offset..offset))
```
Comment (mightyiam) [inline bin/src/traits.rs]: Is this zero-range idiomatic in the usage of ariadne? `offset..offset` feels strange.

Comment (daschinmoy21) [reply bin/src/traits.rs]: Sorry about that. syntax was correct, zero-range was a miss on my end

**Comment by mightyiam** [comment]
Thank you, @daschinmoy21!
